device: /dev/ttyUSB0
baudrate: 1000000

publish_rate: 100 
publish_velocities: false 

servos:
    - id: 2
      joint_name: joint1

    - id: 4
      joint_name: joint2

    - id: 6
      joint_name: joint3

    - id: 8
      joint_name: joint4

    - id: 10
      joint_name: joint5

    - id: 12
      joint_name: joint6

